Fix regexes using invalid escape \p
Introduced in #155. These are invalid, but happen to work on py2. Python
3 rejects them, which will make WB refuse to parse the entire masterlist
when we get to py3:

PS C:\Users\Infernio> py -3
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.compile('UL(E|M|S) .*\patch.esp')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Python39\lib\re.py", line 252, in compile
return _compile(pattern, flags)
File "C:\Python39\lib\re.py", line 304, in _compile
p = sre_compile.compile(pattern, flags)
File "C:\Python39\lib\sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "C:\Python39\lib\sre_parse.py", line 948, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Python39\lib\sre_parse.py", line 443, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
File "C:\Python39\lib\sre_parse.py", line 525, in _parse
code = _escape(source, this, state)
File "C:\Python39\lib\sre_parse.py", line 426, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 12

Edited to move the backslashes to the file extensions instead, where
they were probably intended to be.